export const LABELS = {
  // Page titles
  pages: {
    overview: 'Обзор',
    players: 'Игроки',
    prizes: 'Призы',
    redemptions: 'Использование призов',
    behavior: 'Поведение',
    anomalies: 'Аномалии',
    diagnostics: 'Диагностика',
  },

  // Overview page
  overview: {
    totalUsers: 'Всего пользователей',
    activePlayers: 'Активные игроки за период',
    totalSpins: 'Всего вращений за период',
    welcomeGrants: 'Welcome-призы выданы',
    redeemedPrizes: 'Использовано призов',
    unusedActive: 'Не использовано и активно',
    winRate: 'Доля выигрышей',
    noWinRate: 'Доля "ничего"',
    avgSpinsPerPlayer: 'Среднее число вращений на активного игрока',
    newPlayers: 'Новых игроков за период',
    welcomePrizesUsed: 'Welcome-призов использовано',
    avgIntervalBetweenSpins: 'Средний интервал между вращениями',
    avgLifetimeDays: 'LTV игрока (дней от 2-го до последнего вращения)',
    spinsOverTime: 'Динамика вращений по дням',
    activePlayersOverTime: 'Активные игроки по дням',
    resultDistribution: 'Распределение результатов',
    topPrizesByCount: 'Топ призов по количеству выдач',
    topPrizesByUsage: 'Топ призов по количеству использований',
    topPlayerByRedemptions: 'Топ игрок по использованию призов',
    topPlayerBySpins: 'Топ игрок по количеству вращений',
    topPlayerByValuable: 'Топ игрок по ценным призам',
    fairnessSummary: 'Краткая сводка по fairness',
    anomaliesSummary: 'Краткая сводка по аномалиям',
  },

  // Players page
  players: {
    searchPlaceholder: 'Поиск по имени, username или telegram_id',
    registrationDate: 'Дата регистрации',
    spinsInPeriod: 'Количество вращений за период',
    totalSpins: 'Количество всех вращений за всё время',
    wonPrizes: 'Количество выигранных призов',
    noPrizes: 'Количество "ничего"',
    welcomePrizes: 'Количество welcome-призов',
    redeemedPrizes: 'Количество использованных призов',
    expiredPrizes: 'Количество просроченных неиспользованных призов',
    valuablePrizes: 'Количество ценных призов',
    lastActivity: 'Последняя активность',
    avgInterval: 'Средний интервал между вращениями',
    activeDays: 'Дней активности за период',
    leaderboards: {
      bySpins: 'Лидеры по вращениям',
      byRedeemed: 'Лидеры по использованным призам',
      byWon: 'Лидеры по выигранным призам',
      byValuable: 'Лидеры по ценным призам',
      byExpired: 'Лидеры по просроченным призам',
    },
  },

  // Prizes page
  prizes: {
    name: 'Название',
    description: 'Описание',
    id: 'ID',
    expectedProb: 'Настроенная вероятность',
    actualProb: 'Фактическая вероятность',
    deviation: 'Отклонение',
    grantedInPeriod: 'Выдано за период',
    grantedTotal: 'Выдано за всё время',
    redeemed: 'Использовано',
    usageRateInPeriod: '% использований за период',
    unusedActive: 'Не использовано активно',
    unusedExpired: 'Не использовано просрочено',
    redemptionRate: 'Redemption rate',
    valuableFlag: 'Ценный приз',
    typeWheel: 'Колесо',
    typeWelcome: 'Welcome System Prize',
    fairnessSection: 'Анализ честности',
    expectedVsActual: 'Ожидаемая vs Фактическая вероятность',
  },

  // Redemptions page
  redemptions: {
    totalGranted: 'Всего выдано',
    redeemed: 'Использовано',
    unusedActive: 'Не использовано и активно',
    unusedExpired: 'Не использовано и просрочено',
    redemptionRate: 'Redemption rate',
    expirationRate: 'Expiration rate',
    dailyRedemptions: 'Ежедневные использования',
    dailyExpirations: 'Ежедневные истечения',
    welcomeRedemptions: 'Welcome-призы использованы',
  },

  // Behavior page
  behavior: {
    activityHeatmap: 'Тепловая карта активности (день × час UTC)',
    avgGap: 'Средний промежуток между вращениями',
    medianGap: 'Медиана промежутка между вращениями',
    daysToFirstSpin: 'Дней между регистрацией и первым вращением колеса',
    daysToRedeem: 'Дней между выигрышем и использованием',
    usageDelayDistribution: 'Распределение задержки использования',
    activeDaysPerPlayer: 'Активные дни на игрока',
    repeatPatterns: 'Паттерны повторного участия',
  },

  // Anomalies page
  anomalies: {
    severity: 'Серьезность',
    severityLow: 'Низкая',
    severityMedium: 'Средняя',
    severityHigh: 'Высокая',
    rule: 'Правило',
    entity: 'Объект',
    explanation: 'Объяснение',
    metrics: 'Метрики',
  },

  // Diagnostics page
  diagnostics: {
    duplicateSpins: 'Дублирующиеся вращения',
    nullUserIds: 'Вращения без user_id',
    nullPrizeIds: 'Вращения без prize_id',
    brokenJoins: 'Нарушенные связи',
    invalidTimestamps: 'Некорректные временные метки',
    missingPrizes: 'Призы не найдены в справочнике',
    rowCounts: 'Количество записей',
    dataFreshness: 'Свежесть данных',
    dbConnectivity: 'Подключение к базе данных',
    tableUsers: 'Пользователи',
    tableSpins: 'Вращения',
    tablePrizes: 'Призы',
  },

  // Filters
  filters: {
    today: 'Сегодня',
    last7Days: '7 дней',
    last30Days: '30 дней',
    allTime: 'Всё время',
    customRange: 'Произвольный период',
    dateFrom: 'Дата от',
    dateTo: 'Дата до',
    apply: 'Применить',
    reset: 'Сбросить',
  },

  // Common
  common: {
    loading: 'Загрузка...',
    noData: 'Нет данных',
    error: 'Ошибка',
    total: 'Всего',
    player: 'Игрок',
    prize: 'Приз',
    date: 'Дата',
    count: 'Количество',
    percentage: 'Процент',
    days: 'дней',
    hours: 'часов',
    minutes: 'минут',
    yes: 'Да',
    no: 'Нет',
  },
} as const;
